 
//  export const pizzaItems = [
//   // Veg Pizzas
//   {
//     id: 1,
//     name: "Margherita",
//     category: "veg",
//     image: "path/to/margherita.jpg",
//     description: "Classic Margherita with fresh tomatoes and basil.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 2,
//     name: "Farmhouse",
//     category: "veg",
//     image: "path/to/farmhouse.jpg",
//     description: "Loaded with fresh vegetables like capsicum, tomatoes, and onions.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 3,
//     name: "Peppy Paneer",
//     category: "veg",
//     image: "path/to/peppy-paneer.jpg",
//     description: "Zesty paneer with capsicum and red paprika.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 4,
//     name: "Mexican Green Wave",
//     category: "veg",
//     image: "path/to/mexican-green-wave.jpg",
//     description: "Mexican herbs sprinkled over onion, capsicum, tomato & jalapeno.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 5,
//     name: "Veg Extravaganza",
//     category: "veg",
//     image: "path/to/veg-extravaganza.jpg",
//     description: "A delicious mix of all the veggies you can imagine.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 6,
//     name: "Paneer Makhani",
//     category: "veg",
//     image: "path/to/paneer-makhani.jpg",
//     description: "Rich and creamy paneer makhani topped with soft paneer cubes.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 7,
//     name: "Deluxe Veggie",
//     category: "veg",
//     image: "path/to/deluxe-veggie.jpg",
//     description: "Veggies overload with extra cheese and classic crust.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 8,
//     name: "Veggie Paradise",
//     category: "veg",
//     image: "path/to/veggie-paradise.jpg",
//     description: "A paradise of fresh vegetables with crunchy onions, capsicum, and mushrooms.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 9,
//     name: "Cheese n Corn",
//     category: "veg",
//     image: "path/to/cheese-n-corn.jpg",
//     description: "Sweet and juicy corn with loads of cheese.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 10,
//     name: "Pepper Barbecue Veg",
//     category: "veg",
//     image: "path/to/pepper-barbecue-veg.jpg",
//     description: "Tangy and spicy pepper barbecue sauce with mixed veggies.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },

//   // Non-Veg Pizzas
//   {
//     id: 11,
//     name: "Pepper Barbecue Chicken",
//     category: "nonVeg",
//     image: "path/to/pepper-barbecue-chicken.jpg",
//     description: "Pepper barbecue chicken with spicy and tangy flavors.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 12,
//     name: "Chicken Dominator",
//     category: "nonVeg",
//     image: "path/to/chicken-dominator.jpg",
//     description: "Loaded with double the chicken for the ultimate meat lover.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 13,
//     name: "Chicken Fiesta",
//     category: "nonVeg",
//     image: "path/to/chicken-fiesta.jpg",
//     description: "Topped with spicy chicken and peri-peri chicken chunks.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 14,
//     name: "Peri-Peri Chicken",
//     category: "nonVeg",
//     image: "path/to/peri-peri-chicken.jpg",
//     description: "Fiery peri-peri chicken with onion and capsicum.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 15,
//     name: "Chicken Sausage",
//     category: "nonVeg",
//     image: "path/to/chicken-sausage.jpg",
//     description: "Juicy chicken sausages with spicy seasoning.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 16,
//     name: "Chicken Tikka",
//     category: "nonVeg",
//     image: "path/to/chicken-tikka.jpg",
//     description: "Grilled chicken tikka with onions and capsicum.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 17,
//     name: "Non-Veg Supreme",
//     category: "nonVeg",
//     image: "path/to/non-veg-supreme.jpg",
//     description: "A supreme mix of chicken, lamb, and veggies.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 18,
//     name: "Pepperoni",
//     category: "nonVeg",
//     image: "path/to/pepperoni.jpg",
//     description: "Classic pepperoni with rich mozzarella cheese.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 19,
//     name: "Spicy Chicken Meatball",
//     category: "nonVeg",
//     image: "path/to/spicy-chicken-meatball.jpg",
//     description: "Spicy chicken meatballs with a tangy sauce.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 20,
//     name: "Chicken & Bacon",
//     category: "nonVeg",
//     image: "path/to/chicken-bacon.jpg",
//     description: "Savory chicken and crispy bacon with cheese.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },

//   // Recommended Pizzas (some overlap with veg/nonVeg)
//   {
//     id: 21,
//     name: "Paneer Makhani",
//     category: "recommended",
//     image: "path/to/paneer-makhani.jpg",
//     description: "Rich and creamy paneer makhani topped with soft paneer cubes.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 22,
//     name: "Veg Extravaganza",
//     category: "recommended",
//     image: "path/to/veg-extravaganza.jpg",
//     description: "A delicious mix of all the veggies you can imagine.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 23,
//     name: "Chicken Fiesta",
//     category: "recommended",
//     image: "path/to/chicken-fiesta.jpg",
//     description: "Topped with spicy chicken and peri-peri chicken chunks.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 24,
//     name: "Margherita",
//     category: "recommended",
//     image: "path/to/margherita.jpg",
//     description: "Classic Margherita with fresh tomatoes and basil.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 25,
//     name: "Mexican Green Wave",
//     category: "recommended",
//     image: "path/to/mexican-green-wave.jpg",
//     description: "Mexican herbs sprinkled over onion, capsicum, tomato & jalapeno.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 26,
//     name: "Non-Veg Supreme",
//     category: "recommended",
//     image: "path/to/non-veg-supreme.jpg",
//     description: "A supreme mix of chicken, lamb, and veggies.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 27,
//     name: "Pepperoni",
//     category: "recommended",
//     image: "path/to/pepperoni.jpg",
//     description: "Classic pepperoni with rich mozzarella cheese.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 28,
//     name: "Chicken Tikka",
//     category: "recommended",
//     image: "path/to/chicken-tikka.jpg",
//     description: "Grilled chicken tikka with onions and capsicum.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 29,
//     name: "Paneer & Onion",
//     category: "recommended",
//     image: "path/to/paneer-onion.jpg",
//     description: "Soft paneer and crunchy onion with rich cheese.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
//   {
//     id: 30,
//     name: "Spicy Triple Tango",
//     category: "recommended",
//     image: "path/to/spicy-triple-tango.jpg",
//     description: "A fiery combination of peri-peri chicken, jalapenos, and onions.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: false,
//     symbol: "path/to/non-veg-symbol.jpg",
//   },
//   {
//     id: 31,
//     name: "Classic Veggie",
//     category: "recommended",
//     image: "path/to/classic-veggie.jpg",
//     description: "Simple and tasty with onions, capsicum, and mushrooms.",
//     sizes: ["Regular", "Medium", "Large"],
//     crust: ["Thin", "Cheese Burst", "Classic Hand Tossed"],
//     isVeg: true,
//     symbol: "path/to/veg-symbol.jpg",
//   },
// ];



// export default pizzaItems;




// export const prices = [
//   {
//     vegprices: {
//       Regular: 99,
//       Medium: 199,
//       Large: 399,
//     },
//     nonVegPrices: {
//       Regular: 159,
//       Medium: 299,
//       Large: 499,
//     },
//   },
// ];





export const toppings =[{
  veg: [
    { name: "Extra Cheese", price: 30 },
    { name: "Onion", price: 20 },
    { name: "Capsicum", price: 25 },
    { name: "Mushroom", price: 35 },
    { name: "Paneer", price: 45 },
    { name: "Jalapeno", price: 15 },
    // ... add more veg toppings
  ],
  nonVeg: [
    { name: "Chicken Tikka", price: 60 },
    { name: "Chicken Sausage", price: 55 },
    { name: "Pepperoni", price: 70 },
    { name: "Bacon", price: 80 },
    // ... add more non-veg toppings
  ]
}]
